#!/usr/bin/env bash
#
# Pre-push Git hook.
# Runs PHP CS and ESLint on all PHP and JavaScript files, respectively.
# Furthermore it is verified that the repository contains an .editorconfig file.

repo_dir=$(pwd)

# Define some terminal text color shortcuts
text_red=`tput setaf 1 > /dev/null 2>&1`
text_green=`tput setaf 2 > /dev/null 2>&1`
text_reset=`tput sgr0 > /dev/null 2>&1`

# Check the repository for an .editorconfig file
editor_config_path="$repo_dir/.editorconfig"
if [ ! -f $editor_config_path ]; then
    echo "${text_red}No .editorconfig file found in the repository. Please add and commit the config found at http://github.com/VIISON/style-guide and try again.${text_reset}"
    exit 1
fi

# Run PHP code style check (ignoring warnings)
if [ ! -d "${repo_dir}/vendor/viison/style-guide" ]; then
    echo "${text_red}Cannot run PHP code style check, because the 'viison/style-guide' dependency appears to not be installed. Please run 'composer install' inside $(realpath ${repo_dir}).${text_reset}"
    exit 1
fi
if [ ! -f "${repo_dir}/phpcs.xml" ]; then
    echo "${text_red}Cannot run PHP code style check, because a 'phpcs.xml' was not found in $(realpath ${repo_dir}).${text_reset}"
    exit 1
fi
echo -e "\nComposer package 'viison/style-guide' is installed, running PHP Code Sniffer on all PHP files..."
"${repo_dir}/vendor/bin/phpcs" --warning-severity=0 $repo_dir || exit 1
echo -e "${text_green}PHP code style check passed.${text_reset}\n"

# Check whether we should run ESLint
if [ -f "${repo_dir}/package.json" ]; then
    if [ ! -d "${repo_dir}/node_modules" ]; then
        echo "${text_red}package.json found, but node_modules is missing. Please run 'npm install' inside $(realpath ${repo_dir}).${text_reset}"
        exit 1
    fi
    if [ -d "${repo_dir}/node_modules/viison-style-guide" ]; then
        echo "NPM package 'viison-style-guide' is installed, running ESLint on all JavaScript files..."
        (
            set -e
            # Execute eslint in the worktree to avoid an issue with absolute directory arguments in which the directory
            # is a symbolic link in at least eslint 3.19.0 or its dependencies.
            cd -- "$repo_dir"
            node ./node_modules/eslint/bin/eslint.js --quiet .
        ) || exit 1
        echo -e "${text_green}JavaScript code style check passed.${text_reset}\n"
    fi
fi
