#!/usr/bin/env bash
# Pre-commit Git hook.
# Runs PHP CS on PHP files.
#
# If you absolutely must commit without testing,
# use: git commit --no-verify

repo_dir=$1

# Define some terminal text color shortcuts
text_red=`tput setaf 1 > /dev/null 2>&1`
text_green=`tput setaf 2 > /dev/null 2>&1`
text_reset=`tput sgr0 > /dev/null 2>&1`

# Check the repository for an .editorconfig file
editor_config_path="$repo_dir/.editorconfig"
if [ ! -f $editor_config_path ]; then
    echo "${text_red}No .editorconfig file found in the repository. Please add the config found at http://github.com/VIISON/style-guide and commit again.${text_reset}"
    exit 1;
fi

function source_home_file {
    file="$HOME/$1"
    echo $file
    [[ -f "${file}" ]] && source "${file}"
}

# Inlcude any bash environments to make sure the $PATH is loaded properly
source_home_file ".bash_profile"
source_home_file ".zshrc"
source_home_file ".bashrc"
source_home_file ".profile"

# Check for required packages
type phpcs >/dev/null 2>&1 || { echo >&2 "Failed to check code style, because the require package 'phpcs' is not installed."; exit 1; }

# Determine package paths
phpcs_path=($(which phpcs))
hookPath="`dirname \"$0\"`"

# Check all staged files
filenames=($(git diff --staged --name-only HEAD))
numberFilesChanged="${#filenames[@]}"
errorsFound=0

if [[ $numberFilesChanged > 0 ]];
then
    echo "$numberFilesChanged files were changed, running PHP code style check"
    for i in "${filenames[@]}"
    do
        if [[ $i == *.php ]] && [ -f $i ];
        then
            # Run PHP code style check (ignoring warnings)
            $phpcs_path -p --severity=0 --standard=$hookPath/../../php/php-codesniffer-standard/VIISON/ $i
            checkResult=$?
            if [ ${checkResult} -ne 0 ];
            then
                # File has code style issues
                ((errorsFound++))
            fi
        fi
    done
fi

if [[ ${errorsFound} == 0 ]]
then
    echo "${text_green}PHP code style check passed.${text_reset}"
    exit 0;
else
    echo "${text_red}PHP code style errors were found. Please fix them and commit again.${text_reset}"
    exit 1;
fi
