<?php

class UnitTestClass
{
    /**
     * @testdox some description
     */
    public function test_notSomeDescription(): void
    {
        // Implementation
    }

    /**
     * @testdox Some other description
     */
    public function test_notSomeOtherDescription(): void
    {
        // Implementation
    }

    /**
     * @testdox other-description
     */
    public function test_notOtherDescription(): void
    {
        // Implementation
    }
}
